version: '3.8'

services:
  api : 
    build : 
      dockerfile: Dockerfile
      context: ./api
      target: development
    #Mount host directory to the docker container
    # Mount api directory (./api) to (:) docker container (/dev/src/app)
    # Reflect files change from host to container
    volumes: 
      - ./api:/dev2/src/app
      - /dev2/src/app/node_modules
      #Run indebug mode npm run start :debug => also start your vs code debuger
    # RUN in debug mode: npm run start:debug --> Also start your vscode debugger
    # Run in dev mode: npm run start:dev
    command: npm run start:debug
    depends_on: 
      - mysql
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/db  # Update the connection URL for MySQL
      NODE_ENV: development
      JWT_SECRET: hard_to_guess_secret_123
      PORT: 3000
    ports: 
      - 3000:3000
      - 9229:9229
  chatfrontend:
    build: 
      dockerfile: Dockerfile
      context: ./chatfrontend
      target: development
    command: npm run start
    volumes:
      - ./chatfrontend:/dev2/chatfrontend/src/app
      - /dev2/chatfrontend/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - api
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ahmed  # Remplacez par le mot de passe souhaité
      MYSQL_DATABASE: chat
    ports:
      - 3306:3306

  # The phpMyAdmin tool for managing MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 5050:80
  
    